### ISSUE TITLE
Running the code

### ISSUE THREAD

**Issue by repa86** [ElettraSciComp/Pore3D#2]
Now it is only possible to run the Pore3D in IDL environment?  For this I should by the license for full scope of IDL version? It is not possible to run and use pore3D with IDL virtual machine?
How about using Pore3D with Matlab?

**Comment by franzpx125** [comment]
Pore3D runs within a full IDL environment (no IDL virtual machine). IDL is a commercial product, so your institution requires a full license. There is no porting of Pore3D for MATLAB (similarly, MATLAB is a commercial product so you or your institution would need a license anyway).
